### ISSUE TITLE
Durisimo

### ISSUE THREAD

**Issue by kakachiex2** [blepping/ComfyUI-ApplyResAdapterUnet#1]
Durisimo thanks for the node.

![ResAdapter_Unnofficial_Workflow_V1 0](https://github.com/blepping/ComfyUI-ApplyResAdapterUnet/assets/1762112/6d7a4e48-a7d4-4b3a-ba43-235cd7ce4a38)

**Comment by blepping** [comment]
you're very welcome and thanks for taking the time to comment!
